### ISSUE TITLE
[Enhancement] Allow API port changes for use with side-cars and other scenarios

### ISSUE THREAD

**Issue by aellert** [emberstack/docker-sftp#14]
I'd like to use your image as a sidecar to an existing web server container which already listen to port 80.
Is there any reason to EXPOSE port 80 here : https://github.com/emberstack/docker-sftp/blob/f926252b54cbb6cb7e00cd849020698138d86de8/src/ES.SFTP.Host/Dockerfile#L22 ?

**Comment by winromulus** [comment]
@aellert - EXPOSE in docker files are just developer notes (to indicate that by default this listens on that port). The port 80 is for the API and health checks. You can run this as a side-car without issues.

**Comment by aellert** [comment]
Actually if another container in the same pod use port 80, I got error CrashLoopBackOff from Kubernetes and in docker-sftp logs:
`System.IO.IOException: Failed to bind to address http://[::]:80: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---`

**Comment by winromulus** [comment]
That is not from the EXPOSE, that is from the container definition. Make sure your container ports don't conflict in your deployment.

**Comment by aellert** [comment]
Here is a sample test to demonstrate:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
   matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      - image: emberstack/sftp
        name: sftp
        ports:
        - containerPort: 22
          name: sftp
          protocol: TCP`

**Comment by winromulus** [comment]
In this scenario your only option would be to change NGINX to run on a different port since they are both inside the same pod. SFTP needs to run the API (which does not support changing the port at this time) in order to be notified via host events about logins (and prepare the user's session) and for health checks.
My suggestion is to set nginx to some other port. If this is not feasible, I could set this as a possible enhancement but you will have to wait for this to be implemented.

**Comment by aellert** [comment]
the EXPOSE 80 is hardcoded into most of web server docker images, it would be great if you could hardcode another random port or add an option to override the default port 80

**Comment by winromulus** [comment]
@aellert - The API is now running on 25080 to avoid such conflicts. Please use the new release image and let me know if this works for you.

**Comment by aellert** [comment]
Hi Romeo,

Yes, this works for me.
Thanks for your great job !

Alexandre.

Le sam. 2 mai 2020 à 13:19, Romeo Dumitrescu <notifications@github.com> a
écrit :
