### ISSUE TITLE
Require both publickey and password

### ISSUE THREAD

**Issue by fintechestenberg** [emberstack/docker-sftp#140]
I am trying to require a login to need both key and password to login, but it seems that when publickeys is set it ignores the password.

my user config is like this
```

        {
            "Username": "test",
            "Password": "1234",
            "PublicKeys": [
                "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMmM0HScbma4pxSq+9Pfg8MitDwKPza6pA5tqBCTAcAF test@test.com
            ]
        }
```

Is there any special flag or similar that needs to be set to enable this?

**Comment by OvrAp3x** [comment]
I made a fix, 
https://github.com/emberstack/docker-sftp/pull/141

**Comment by niteshamin** [comment]
Any chance we can get this approved and merged into a new build.
Got a use case which can benefit from it.

**Comment by winromulus** [comment]
@niteshamin should be available soon (building)
