### ISSUE TITLE
Huge amount of zombie processes coming from failed login attempts

### ISSUE THREAD

**Issue by dimitrivdw** [emberstack/docker-sftp#19]
![image](https://user-images.githubusercontent.com/65605977/82330705-79e68d80-99e3-11ea-951b-f32e506beda4.png)

![image](https://user-images.githubusercontent.com/65605977/82330973-c9c55480-99e3-11ea-90c3-4f1f2fb3e2e1.png)

For every failed connection attempt, there seems to be a new zombie process, which eventually kills my host, because there are no free PIDs left. For now, I'm restarting the container every day to avoid this issue, but if this could get fixed, that would be great!

This is version 2.1.14

Thanks!

**Comment by winromulus** [comment]
Hi @dimitrivdw 
This is not an issue with the implementation, but an issue with OpenSSH.
I've noticed this as well and it looks like a known problem (a search online for SSH zombie processes will show the same). My suggestion is to install fail2ban (you'll need a custom image) or find a way to protect your SFTP server from being hit constantly with invalid credentials.
In the next version I will add liveness probes which will basically restart the pod if a connection cannot be established, but this will only partially fix your issue.
I will close this issue for now. If you can, join our Slack (see README for invitation link) and we can continue the discussion on how to best mitigate this issue there.
