### ISSUE TITLE
can't connect to sftp after pod is running for a while

### ISSUE THREAD

**Issue by mazdack** [emberstack/docker-sftp#32]
looks like after a certain amount of time, sshd process in the container goes down and it's not possible to connect to stfp nor from inside the container, nor from outside

![image](https://user-images.githubusercontent.com/6659876/86111724-655be180-bac7-11ea-84b9-2ae3b8b5e2aa.png)

**Comment by winromulus** [comment]
Info export:
Screenshot provided shows sshd process missing
- suspected: tini lost the sshd process or something killed it
- resolution: add monitoring for the sshd process so the dotnet application will restart the process
