### ISSUE TITLE
[Question] Permission denied using default configuration

### ISSUE THREAD

**Issue by fdo13100** [emberstack/docker-sftp#37]
Hi,

I'm trying to change default login/password using Helm. I use this values file : 

**configuration:
  Users:
    - Username : toto
        Password : toto**

I can login but when I try to create a directory, I got :
_sftp> mkdir test
Couldn't create directory: Permission denied_

What stupid mistake did I do ?

Thanks

**Comment by winromulus** [comment]
If you're using the default configuration, make sure you're in the `sftp` directory. The default configuration sets all users chroot to /home/<user>/sftp. That means they have read/write only in /sftp
A standard SFTP client follows the start path and goes into /sftp directly but I think you're in /home/user.
If you want to confirm, after you connect, do a `ls` and if you see an sftp dir, that means your client did not respect the start dir command and you have to manually `cd sftp`. WinSCP/FileZilla/any other standard client will go into /sftp directly

**Comment by fdo13100** [comment]
ok thx a lot !

**Comment by Meghana-V** [comment]
Hi,
I am facing similar issue. 
I am unable to run `cd sftp` throws an error `Couldn't stat remote file: No such file or directory`. 
When i run `pwd` it gives `/`
Please help me to create a directory.

**Comment by ItaiCovver** [comment]
> Hi, I am facing similar issue. I am unable to run `cd sftp` throws an error `Couldn't stat remote file: No such file or directory`. When i run `pwd` it gives `/` Please help me to create a directory.

I am facing the same issue after connecting via the CLI

```
sftp Username@host
(Username@host) Password:
Connected to host
sftp> pwd
Remote working directory: /
sftp> mkdir test
remote mkdir "/test": Permission denied
```
