### ISSUE TITLE
[Question] How to use persistent storage

### ISSUE THREAD

**Issue by muradheydarov** [emberstack/docker-sftp#49]
How can I use storageClass for persist my data? I can not find any setting about that

**Comment by winromulus** [comment]
Hi @muradheydarov 

Because different people have different strategies for storage of the data (some use a single PV for all data, while others separate by users etc), you need to create your own PV with your storage class and use the following to attach them to their respective locations:
```
storage:
  volumeMounts: []
  volumes: []
```
