### ISSUE TITLE
Add an annotation hook to restart pod after config change

### ISSUE THREAD

**Issue by VictorGetz** [emberstack/docker-sftp#52]
Please look at my Pull Request #51 before it gets closed

We used docker-sftp helm chart and recognized that the configuration changes were not automatically applied when we deployed the helm chart.

A good solution would be to add a config checksum like described here https://helm.sh/docs/howto/charts_tips_and_tricks/

**Comment by winromulus** [comment]
@VictorGetz - as mentioned on the PR, the application should pick up configuration changes. If this does not happen, we have a bug.
Please post your logs here or join our Slack channel for debugging.

**Comment by VictorGetz** [comment]
From https://kubernetes.io/docs/concepts/configuration/secret/
Note: A container using a Secret as a subPath volume mount will not receive Secret updates.

 ```
          {{- if .Values.configuration }}
            - name: sftp-json
              mountPath: "/app/config/sftp.json"
              subPath: sftp.json
              readOnly: true
          {{- end }}
```

I will join you in slack :+1:

**Comment by VictorGetz** [comment]
Slack invite link expired
