### ISSUE TITLE
Overide config for 1 master User

### ISSUE THREAD

**Issue by willoups** [emberstack/docker-sftp#58]
I try to overide sftp.json for create a user able to access to other users directory.
My file:
{
  "Global": {
    "Chroot": {
      "Directory": "%h",
      "StartPath": "sftp"
    },
    "Directories": ["sftp"]
  },
  "Users": [
    {
      "Username": "toto",
      "Password": "titi"
    },
    {
      "Username": "master",
      "Password": "password",
      "Chroot": {
        "Directory": "/",
        "StartPath": "/"
      }
    }
  ]
}

if you have sugggestion

**Comment by ilkinmammadzada** [comment]
Same issue. Duplicate: [https://github.com/emberstack/docker-sftp/issues/57](url)

**Comment by winromulus** [comment]
Indeed, issue is duplicate. Closing. Please see #57
