### ISSUE TITLE
password is in plaintext - default or advanced configuration

### ISSUE THREAD

**Issue by thulasi3** [emberstack/docker-sftp#8]
Hi, It's feature request..

Now when we set custom username and password in the configuration section, username and password goes in plain text. Anyway to configure as secret? If not, How to store encrypted password using `configuration.Users[].PasswordIsEncrypted`.

Eventhough it's sftp, why we need to keep username and password in plain text?

**Comment by winromulus** [comment]
Hi,

The password is plain text only inside the container and it does get encrypted after the user is created. If you already have encrypted passwords, you can set the value in the password field and set PasswordIsEncrypted to true.
If you want to encrypt your password, please use 
```echo -n "your-password" | docker run -i --rm atmoz/makepasswd --crypt-md5 --clearfrom=-``` 
to encrypt it.

**Comment by winromulus** [comment]
Also, the configuration is stored in a secret that is mounted, not as plain text. That field only indicates that the password value has been pre-encrypted (for example importing users with encrypted passwords from an existing system)

**Comment by winromulus** [comment]
I'm closing this issue if there are no other questions. Please reopen otherwise.
