### ISSUE TITLE
Folder created with root

### ISSUE THREAD

**Issue by DRAKUN** [emberstack/docker-sftp#9]
Impossible to add file because folders have been created by root in my KUBERNETES cluster
<img width="532" alt="image" src="https://user-images.githubusercontent.com/366065/77245353-458e6500-6c1e-11ea-824f-85b63d382208.png">

root 

![image](https://user-images.githubusercontent.com/366065/77245396-a027c100-6c1e-11ea-958e-72dfb163c6fb.png)

```sh
# Default values for sftp.
replicaCount: 1
image:
  repository: emberstack/sftp
  pullPolicy: Always

configuration:
  Users:
    - Username: "foo"
      Password: "pass"
      Chroot: "%h"
      StartPath: "IOTA"
      Directories: ["exo"]

  Global:
    #Chroot:
    #  StartPath: "IOTA"
    Directories:
      - "IOTA/IN"
      - "IOTA/OK"
      - "IOTA/KO"
      - "IOTA/LOG"

storage:
  volumeMounts:
    - name: sftp-data
      mountPath: /home/foo/IOTA
  volumes:
    - name: sftp-data
      persistentVolumeClaim:
        claimName: sftp-data-pvc
service:
  type: ClusterIP
  port: 22
resources:
  limits:
    cpu: 400m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

**Comment by winromulus** [comment]
Hi @DRAKUN ,
Fort CHROOT to work, root has to own all the file path up to the user's directories.
That being said, can you send me version you are using and a complete tree of /home/foo please?
As a note. the permissions for the user directories are set on user logon, but there might be a bug there.
Thanks.

**Comment by DRAKUN** [comment]
Hi
```sh
Statut :         	Connexion à 127.0.0.1:2222...
Réponse :     	fzSftp started, protocol_version=9
Commande :	open "foo@127.0.0.1" 2222
Erreur :         	FATAL ERROR: Connection refused
Erreur :         	Impossible de récupérer le contenu du dossier
Statut :         	Déconnecté du serveur
Statut :         	Connexion à 127.0.0.1:2222...
Réponse :     	fzSftp started, protocol_version=9
Commande :	open "foo@127.0.0.1" 2222
Erreur :         	FATAL ERROR: Connection refused
Erreur :         	Impossible d'établir une connexion au serveur
Statut :         	Attente avant nouvel essai...
Statut :         	Connexion à 127.0.0.1:2222...
Statut :         	Connected to 127.0.0.1
Statut :         	Récupération du contenu du dossier...
Statut :         	Listing directory /
Statut :         	Contenu du dossier "/" affiché avec succès
Statut :         	Récupération du contenu du dossier "/IOTA"...
Statut :         	Listing directory /IOTA
Statut :         	Contenu du dossier "/IOTA" affiché avec succès
Statut :         	Récupération du contenu du dossier "/IOTA/IN"...
Statut :         	Listing directory /IOTA/IN
Statut :         	Contenu du dossier "/IOTA/IN" affiché avec succès
Statut :         	Connexion à 127.0.0.1:2222...
Statut :         	Connected to 127.0.0.1
Statut :         	Démarrage de l'envoi de /Users/d3n/ressources/DATA/110544_220073_20200317123324929000.xml
Statut :         	Transfert de fichier réussi, 8350 octets transférés en 1 seconde
Statut :         	Récupération du contenu du dossier "/IOTA"...
Statut :         	Listing directory /IOTA
Statut :         	Contenu du dossier "/IOTA" affiché avec succès
Statut :         	Démarrage de l'envoi de /Users/d3n/ressources/DATA/110544_220073_20200317123324929000.xml
Commande :	cd "/IOTA/IN"
Réponse :     	New directory is: "/IOTA/IN"
Commande :	put "/Users/d3n/ressources/DATA/110544_220073_20200317123324929000.xml" "110544_220073_20200317123324929000.xml"
Erreur :         	/IOTA/IN/110544_220073_20200317123324929000.xml: open for write: permission denied
Erreur :         	Échec du transfert du fichier
Statut :         	Démarrage de l'envoi de /Users/d3n/ressources/DATA/110544_220073_20200317123324929000.xml
Statut :         	Récupération du contenu du dossier "/IOTA/IN"...
Statut :         	Listing directory /IOTA/IN
Commande :	put "/Users/d3n/ressources/DATA/110544_220073_20200317123324929000.xml" "110544_220073_20200317123324929000.xml"
Erreur :         	/IOTA/IN/110544_220073_20200317123324929000.xml: open for write: permission denied
Erreur :         	Échec du transfert du fichier
Statut :         	Démarrage de l'envoi de /Users/d3n/ressources/DATA/110544_220073_20200317123324929000.xml
Statut :         	Récupération du contenu du dossier "/IOTA/IN"...
Statut :         	Listing directory /IOTA/IN
Commande :	put "/Users/d3n/ressources/DATA/110544_220073_20200317123324929000.xml" "110544_220073_20200317123324929000.xml"
Erreur :         	/IOTA/IN/110544_220073_20200317123324929000.xml: open for write: permission denied
Erreur :         	Échec du transfert du fichier
Statut :         	Récupération du contenu du dossier "/IOTA/IN"...
Statut :         	Listing directory /IOTA/IN
Statut :         	Contenu du dossier "/IOTA/IN" affiché avec succès
```

**Comment by winromulus** [comment]
What version are you running?

**Comment by DRAKUN** [comment]
version  2.0.17
in kubernetes with helm 
sftp tools 1 2020-03-22 16:45:56.381179 +0100 CET deployed sftp-2.0.17 2.0.17

**Comment by winromulus** [comment]
Hi @DRAKUN 
Found the issue and it should be fixed in v.2.0.18
Try updating and let me know if it solved your issue.

Also, in your configuration, the Chroot section is not correct. It should be:
```
Chroot:
  Directory: "%h"
  StartPath: "IOTA"
```
Please let me know if this fixed your issue

**Comment by DRAKUN** [comment]
OKay , Its work (folder are accesible with the good rights) 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/366065/77418926-dfdddc80-6dc7-11ea-9f8b-c6a52f777ea6.png">


![image](https://user-images.githubusercontent.com/366065/77417319-78269200-6dc5-11ea-8df7-39a23230bce2.png)

But, i see when my application move some files , rights became root:root 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/366065/77418845-c5a3fe80-6dc7-11ea-812c-296193251c78.png">

**Comment by winromulus** [comment]
Where are those files saved? (complete path)
And are you moving those files there using SFTP?

**Comment by DRAKUN** [comment]
ok , my application keep file in folder IN do some chek, and if its doesn't work , they move it in folder KO but when its move right are change.

![image](https://user-images.githubusercontent.com/366065/77419354-8de98680-6dc8-11ea-8851-b90a7a494245.png)

**Comment by winromulus** [comment]
So your application creates the file in "IN" via SFTP upload?

**Comment by DRAKUN** [comment]
Yes

**Comment by winromulus** [comment]
And the move happens also via SFTP?

**Comment by DRAKUN** [comment]
> And the move happens also via SFTP?

Yes

**Comment by winromulus** [comment]
I just tried it out and the permissions are set correctly.
Created a file in IN (owner is foo), created file in OUT (owner is foo). What exactly is your process of moving the file? If you run "mv" as a script from inside the container, that script is run by root

**Comment by DRAKUN** [comment]
yeah i think it is the problem application is a spring boot and it run by root account in a container

**Comment by winromulus** [comment]
Yeah, that runs as root so when the move occurs, it sets the owner as root. My recommendation is to do the swap via SFTP for easy permissions.

**Comment by DRAKUN** [comment]
to do the swap ?

**Comment by winromulus** [comment]
I mean move from IN to OUT. Otherwise you will have to set the permissions after the move to allow the user to access those files.
I'm going to close this issue since the SFTP part was fixed and this is no longer related.

Thanks for identifying the bug and if you have further issues, please report them and I'll do my best to help.

**Comment by DRAKUN** [comment]
okay, thanks you for your help,
last question : is it possible to define a user to root rather than foo ?

**Comment by winromulus** [comment]
@DRAKUN you cannot define the user root but you can specify the user UID and GID. I would not recommend running anything as root or UID'ing to root.
In your scenario, try to have the spring application do a chown on that file to user "foo" after it does the move.
