### ISSUE TITLE
Documentation - Preserve SSH keys

### ISSUE THREAD

**Issue by mgutt** [emberstack/docker-sftp#96]
At the moment the container gets a new SSH key on every creation. To reserve the SSH key, it's needed to mount /etc/ssh. As this seems to be possible, I like to see this as an official option in the documentation.

Example of the mounted ssh dir:
![image](https://user-images.githubusercontent.com/10757176/151720350-afe31e11-5946-4af9-b848-61631e8b4e44.png)

**Comment by winromulus** [comment]
This is supported via the config. Needs to be documented.

**Comment by artisticcheese** [comment]
Is there thorough documentation available for config file? What values shall be there for host keys?

**Comment by mgutt** [comment]
> What values shall be there for host keys?
Those files are created automatically on installation?!
