### ISSUE TITLE
This service allows sftp connections only

### ISSUE THREAD

**Issue by pedrodomingues-ze** [emberstack/docker-sftp#97]
I'm trying to use `scp` to copy files to the container, but it fails with this error: 

![image](https://user-images.githubusercontent.com/83245527/153000125-05e46cba-d11b-41c0-bb2a-d544edac69d7.png)

Is there any way to reconfigure the sshd server to allow SSH connections?

Thanks in advance.

**Comment by winromulus** [comment]
Hi. No, this was never intended to allow SSH connections (for security reasons).
