### ISSUE TITLE
Enhancement: Use without config file: provide default behaviour

### ISSUE THREAD

**Issue by kale1d0code** [emberstack/docker-sftp#99]
like in atmoz/sftp
it is possible to add a string of user:pass as a command to the container
can the same be possible here

**Comment by winromulus** [comment]
Hi @kale1d0code 

Contribution for this would be appreciated but considering the complexity of adding permissions and other settings that might be needed, I'm not sure how useful this might be on it's own. But if this is useful for you, I'll happily review any code changes.
